name: Setup Redmine
description: Setup Redmine or its distribution for testing
author: hidakatsuya
branding:
  icon: download
  color: blue

inputs:
  repository:
    description: 'Redmine repository to setup. Default is redmine/redmine.'
    required: true
    default: 'redmine/redmine'
  version:
    description: 'The branch, tag or commit to checkout. Default is master.'
    required: true
    default: 'master'
  database:
    description: 'Database to use for testing. Possible values are sqlite3 or PostgreSQL and MySQL Docker official image tags (e.g. postgres:14, mysql:8.4.0). Default is sqlite3'
    required: true
    default: 'sqlite3'
  ruby-version:
    description: "Ruby version to use for testing. See ruby/setup-ruby's ruby-version input for available versions."
    required: true
  path:
    description: 'Directory to setup Redmine. Default is the current directory.'
    required: true
    default: '.'

runs:
  using: composite

  steps:
    - name: Set up environment
      run: |
        echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
        echo "RAILS_ENV=test" >> $GITHUB_ENV
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Checkout Redmine source code
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.version }}
        path: ${{ inputs.path }}

    - name: Install dependencies
      run: |
        sudo apt-get update; \
        sudo apt-get install -y --no-install-recommends \
          build-essential \
          bzr git mercurial subversion cvs \
          ghostscript \
          gsfonts \
          imagemagick libmagick++-dev \
          libnss3-dev;
      shell: bash

    - name: Allow ImageMagick to read PDF files
      run: |
        sudo sed -ri 's/(rights)="none" (pattern="PDF")/\1="read" \2/' /etc/ImageMagick-6/policy.xml
      shell: bash

    - name: Set up Google Chrome for system tests
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends google-chrome-stable

        echo GOOGLE_CHROME_OPTS_ARGS="headless,disable-gpu,no-sandbox,disable-dev-shm-usage" >> $GITHUB_ENV
      shell: bash

    - name: Set up PostgreSQL database connection for testing
      if: ${{ startsWith(inputs.database, 'postgres:') }}
      run: |
        sudo apt-get install -y --no-install-recommends libpq-dev

        docker run \
          --name redmine-postgres \
          -e POSTGRES_PASSWORD=postgres \
          -p 5432:5432 \
          -d ${{ inputs.database }}

        cat <<EOS > config/database.yml
          test:
            adapter: postgresql
            database: redmine_test
            encoding: utf8
            host: localhost
            port: 5432
            username: postgres
            password: postgres
        EOS
      shell: bash
      working-directory: ${{ inputs.path }}

    - name: Set up MySQL database connection for testing
      if: ${{ startsWith(inputs.database, 'mysql:') }}
      run: |
        sudo apt-get install -y --no-install-recommends default-mysql-client

        docker run \
          --name redmine-mysql \
          -e MYSQL_ROOT_PASSWORD=password \
          -e MYSQL_DATABASE=redmine_test \
          -p 3306:3306 \
          -d ${{ inputs.database }} \
          --character-set-server=utf8mb4 \
          --collation-server=utf8mb4_unicode_ci

        cat <<EOS > config/database.yml
          test:
            adapter: mysql2
            database: redmine_test
            host: 127.0.0.1
            port: 3306
            username: root
            password: password
            encoding: utf8mb4
        EOS
      shell: bash
      working-directory: ${{ inputs.path }}

    - name: Set up SQLite3 database connection for testing
      if: ${{ inputs.database == 'sqlite3' }}
      run: |
        sudo apt-get install -y --no-install-recommends libsqlite3-dev

        cat <<EOS > config/database.yml
          test:
            adapter: sqlite3
            database: db/test.sqlite3
        EOS
      shell: bash
      working-directory: ${{ inputs.path }}

    - name: Adjust Gemfile
      run: |
        # Ref: https://github.com/agileware-jp/redmine-plugin-orb/pull/70
        # https://www.redmine.org/issues/40802
        if grep -q "require 'blankslate'" lib/redmine/views/builders/structure.rb
        then
          echo 'gem "blankslate"' >> Gemfile
        fi
      shell: bash
      working-directory: ${{ inputs.path }}

    - name: Set up Ruby and install dependencies
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler-cache: true
        working-directory: ${{ inputs.path }}

    - name: Set up database
      run: |
        bin/rails db:create db:migrate
      shell: bash
      working-directory: ${{ inputs.path }}
