name: Setup Redmine
description: Setup Redmine or its distribution for testing
author: hidakatsuya

inputs:
  repository:
    description: 'Redmine repository to setup.'
    required: true
    default: 'redmine/redmine'
  version:
    description: 'The branch, tag or SHEA of the repository to setup.'
    required: true
    default: 'master'
  database:
    description: 'Database to use for testing. Available values are sqlite3, postgresql.'
    required: true
    default: 'sqlite3'
  ruby-version:
    description: "Ruby version to use for testing. See ruby/setup-ruby's ruby-version input for available versions."
    required: true
  path:
    description: 'Directory to setup Redmine.'
    required: true
    default: '.'

runs:
  using: composite

  steps:
    - name: Set up environment
      run: |
        echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
        echo "RAILS_ENV=test" >> $GITHUB_ENV
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Checkout Redmine source code
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.version }}
        path: ${{ inputs.path }}

    - name: Install dependencies
      run: |
        sudo apt-get update; \
        sudo apt-get install -y --no-install-recommends \
          build-essential \
          bzr git mercurial subversion cvs \
          ghostscript \
          gsfonts \
          imagemagick libmagick++-dev \
          libnss3-dev;
      shell: bash

    - name: Allow ImageMagick to read PDF files
      run: |
        sudo sed -ri 's/(rights)="none" (pattern="PDF")/\1="read" \2/' /etc/ImageMagick-6/policy.xml;
      shell: bash

    - name: Set up Google Chrome for system tests
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list && \
        apt-get update && apt-get install -y --no-install-recommends google-chrome-stable; \

        echo GOOGLE_CHROME_OPTS_ARGS="headless,disable-gpu,no-sandbox,disable-dev-shm-usage" >> $GITHUB_ENV
      shell: bash

    - name: Set up PostgreSQL database connection for testing
      if: ${{ inputs.database == 'postgresql' }}
      run: |
        sudo apt-get install -y libpq-dev

        docker run \
          --name redmine-postgres \
          -e POSTGRES_PASSWORD=postgres \
          -p 5432:5432 \
          -d postgres:14

        cat <<EOS > config/database.yml
          test:
            adapter: postgresql
            database: redmine_test
            encoding: utf8
            host: localhost
            port: 5432
            username: postgres
            password: postgres
        EOS
      shell: bash
      working-directory: ${{ inputs.path }}

    - name: Set up SQLite3 database connection for testing
      if: ${{ inputs.database == 'sqlite3' }}
      run: |
        sudo apt-get install -y libsqlite3-dev

        cat <<EOS > config/database.yml
          test:
            adapter: sqlite3
            database: db/test.sqlite3
        EOS
      shell: bash
      working-directory: ${{ inputs.path }}

    - name: Set up Ruby and install dependencies
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler-cache: true
        working-directory: ${{ inputs.path }}

    - name: Set up database
      run: |
        bin/rails db:create db:migrate
      shell: bash
      working-directory: ${{ inputs.path }}
